env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./frontend/tsconfig.json
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
rules: 
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
