version: "3.7"

services:
    expedition3gpp:
        image: monandkey/expedition3gpp:latest
        container_name: expedition3gpp
        volumes:
            - "./:/home/expedition3gpp/container:rw"
        hostname: expedition3gpp
        command: /bin/sh -c "while :; do sleep 10; done"
