version: "3.7"

# Volume Define
# volumes:
#     ruby_volume:

services:
    ruby:
        image: golang:latest
        container_name: golang-dev
        volumes:
            - "./:/home:rw"
        hostname: golang-dev
        command: /bin/sh -c "while :; do sleep 10; done"
